version: '2'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'tuda@123'
    volumes:
      - ./initsql:/docker-entrypoint-initdb.d
  redis:
    image: redis
  zookeeper:
    image: jplock/zookeeper
  disconf:
    build: .
    ports:
      - "8080"
    volumes:
      - ./disconf:/disconf
    depends_on:
      - mysql
      - redis 
      - zookeeper
